### ISSUE TITLE
Is it possible to use the web application separately? 

### ISSUE THREAD

**Issue by Aria-K-Alethia** [soupdtag/speak-tool#1]
Hi,

Thank you for sharing your code.
I plan to use another crowd-sourcing platform to collect data, so I wonder if it is possible to use the web application separately.
Sorry for that but I haven't delved into your code. If possible, it would be appreciated if you could provide a brief guide for this.

Thank you for your time.

**Comment by soupdtag** [comment]
Short answer is **yes; the web application runs completely independently of Amazon Mechanical Turk.**

If you use a different crowdsourcing platform, there are two design considerations that will be important to address:

- The web application is integrated into MTurk by embedding the website as a custom HTML element into MTurk HITs. **_I assume the crowdsourcing platform you have in mind also has some way to embed custom HTML elements (or at least a URL) in their crowdsourcing tasks - you will have to configure your crowdsourcing platform accordingly._**
- The only part of the web app that interacts with MTurk is in `app.py` steps 4 and 5 (lines 170-302), which is where the web application submits basic log information to MTurk at the completion of the task. **_You would have to review and edit the code in this step, so that the web app sends the information to your crowdsourcing platform instead of MTurk._**

Hope this helps!

**Comment by Aria-K-Alethia** [comment]
Got it.
Thank you for your help!
